# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blender_shadow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blender_shadow.proto',
  package='blender_shadow_worker',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x62lender_shadow.proto\x12\x15\x62lender_shadow_worker\"3\n\x05Numpy\x12\r\n\x05\x64type\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"9\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08target_x\x18\x02 \x01(\x02\x12\x10\n\x08target_y\x18\x03 \x01(\x02\"D\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\t\x12,\n\x06render\x18\x02 \x01(\x0b\x32\x1c.blender_shadow_worker.Numpy2\\\n\rBlenderShadow\x12K\n\x06GetVal\x12\x1e.blender_shadow_worker.Request\x1a\x1f.blender_shadow_worker.Response\"\x00\x62\x06proto3')
)




_NUMPY = _descriptor.Descriptor(
  name='Numpy',
  full_name='blender_shadow_worker.Numpy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dtype', full_name='blender_shadow_worker.Numpy.dtype', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='blender_shadow_worker.Numpy.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='blender_shadow_worker.Numpy.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=98,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='blender_shadow_worker.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='blender_shadow_worker.Request.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_x', full_name='blender_shadow_worker.Request.target_x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_y', full_name='blender_shadow_worker.Request.target_y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=157,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='blender_shadow_worker.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='blender_shadow_worker.Response.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='render', full_name='blender_shadow_worker.Response.render', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=227,
)

_RESPONSE.fields_by_name['render'].message_type = _NUMPY
DESCRIPTOR.message_types_by_name['Numpy'] = _NUMPY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Numpy = _reflection.GeneratedProtocolMessageType('Numpy', (_message.Message,), dict(
  DESCRIPTOR = _NUMPY,
  __module__ = 'blender_shadow_pb2'
  # @@protoc_insertion_point(class_scope:blender_shadow_worker.Numpy)
  ))
_sym_db.RegisterMessage(Numpy)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'blender_shadow_pb2'
  # @@protoc_insertion_point(class_scope:blender_shadow_worker.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'blender_shadow_pb2'
  # @@protoc_insertion_point(class_scope:blender_shadow_worker.Response)
  ))
_sym_db.RegisterMessage(Response)



_BLENDERSHADOW = _descriptor.ServiceDescriptor(
  name='BlenderShadow',
  full_name='blender_shadow_worker.BlenderShadow',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=229,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetVal',
    full_name='blender_shadow_worker.BlenderShadow.GetVal',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLENDERSHADOW)

DESCRIPTOR.services_by_name['BlenderShadow'] = _BLENDERSHADOW

# @@protoc_insertion_point(module_scope)
